In [3]:
from importlib import reload
import sys
from pathlib import Path

src_path = (Path.cwd().parent / "src").resolve()
if str(src_path) not in sys.path:
    sys.path.insert(0, str(src_path))

import dictionary_match
import embedder
dictionary_match = reload(dictionary_match)
embedder = reload(embedder)

from dictionary_match import compute_dictionary_pairs_and_topk, dumps_skill_columns
from dictionary_match import to_skill_list

from embedder import TextEmbedder, compute_text_pairs_and_topk

import json
import pandas as pd

processed_dir = "../data/processed"

c:\Users\yukki\Documents\Grad-projects\resume-job-matcher\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [4]:
resume_ranked_path = f"{processed_dir}/resume_skills_extracted.csv"
job_ranked_path = f"{processed_dir}/job_skills_extracted.csv"

resume_out = pd.read_csv(resume_ranked_path)
job_out = pd.read_csv(job_ranked_path)
print("Loaded ranked extracted files")

Loaded ranked extracted files

# TF-IDF

In [5]:
embedder = "tfidf"

model_pairs_df, model_topk_df = compute_text_pairs_and_topk(
    resume_df=resume_out,
    job_df=job_out,
    model_name=embedder,
)

In [6]:
display(model_topk_df.head())
display(model_pairs_df.head())

,resume_id,resume_idx,job_idx,job_title,company,job_location,model_name,semantic_similarity,final_score,rank
0,20345168,0,715,Payroll Manager,MetroMSR - Staffing Resources,"Alexandria, VA",tfidf,0.2336,23.36,1
1,20345168,0,1445,Senior Accountant Tax,Paragon Accountants,"San Diego, CA",tfidf,0.2022,20.22,2
2,20345168,0,2937,***Accounting Senior Manager | Hybrid in Tampa...,Vaco,"Tampa, FL",tfidf,0.1968,19.68,3
3,20345168,0,808,Controller,Chesapeake Contracting Group,"Baltimore, MD",tfidf,0.1935,19.35,4
4,20345168,0,2099,Senior Accountant,Jobot,"Los Angeles, CA",tfidf,0.1885,18.85,5

,resume_id,resume_idx,job_idx,job_title,company,job_location,model_name,semantic_similarity,final_score
0,20345168,0,0,Registered Nurse (RN) at Aveanna,Health eCareers,"Vancouver, WA",tfidf,0.0118,1.18
1,20345168,0,1,Locum | Physician Obstetrics and Gynecology,Weatherby Healthcare,"New Richmond, WI",tfidf,0.0100,1.00
2,20345168,0,2,Technology Sales (Recruiting) Business Develop...,Proven Recruiting,"Austin, TX",tfidf,0.0270,2.70
3,20345168,0,3,Travel RN Oncology 1862.00/week - 23731031EXPP...,TravelNurseSource,"Lexington, KY",tfidf,0.0080,0.80
4,20345168,0,4,Floor Supervisor Full Time - TOMMY HILFIGER - ...,Tommy Hilfiger,"Las Vegas, NV",tfidf,0.0375,3.75

# BGE-SMALL

In [8]:
embedder = "BAAI/bge-small-en-v1.5"

model_pairs_df, model_topk_df = compute_text_pairs_and_topk(
    resume_df=resume_out,
    job_df=job_out,
    model_name=embedder,
)

Loading weights: 100%|██████████| 199/199 [00:00<00:00, 6701.51it/s]
BertModel LOAD REPORT from: BAAI/bge-small-en-v1.5
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

In [9]:
display(model_topk_df.head())
display(model_pairs_df.head())

,resume_id,resume_idx,job_idx,job_title,company,job_location,model_name,semantic_similarity,final_score,rank
0,20345168,0,698,Sr. Staff Accountant,Robert Half,"Avondale, PA",BAAI/bge-small-en-v1.5,0.8165,81.65,1
1,20345168,0,1093,Staff Accountant,Accounting Career Consultants & HR Career Cons...,"St Louis, MO",BAAI/bge-small-en-v1.5,0.8112,81.12,2
2,20345168,0,280,Staff Accountant,Willamette Falls Paper Company,"West Linn, OR",BAAI/bge-small-en-v1.5,0.8070,80.70,3
3,20345168,0,715,Payroll Manager,MetroMSR - Staffing Resources,"Alexandria, VA",BAAI/bge-small-en-v1.5,0.7959,79.59,4
4,20345168,0,1445,Senior Accountant Tax,Paragon Accountants,"San Diego, CA",BAAI/bge-small-en-v1.5,0.7919,79.19,5

,resume_id,resume_idx,job_idx,job_title,company,job_location,model_name,semantic_similarity,final_score
0,20345168,0,0,Registered Nurse (RN) at Aveanna,Health eCareers,"Vancouver, WA",BAAI/bge-small-en-v1.5,0.6605,66.05
1,20345168,0,1,Locum | Physician Obstetrics and Gynecology,Weatherby Healthcare,"New Richmond, WI",BAAI/bge-small-en-v1.5,0.6696,66.96
2,20345168,0,2,Technology Sales (Recruiting) Business Develop...,Proven Recruiting,"Austin, TX",BAAI/bge-small-en-v1.5,0.6966,69.66
3,20345168,0,3,Travel RN Oncology 1862.00/week - 23731031EXPP...,TravelNurseSource,"Lexington, KY",BAAI/bge-small-en-v1.5,0.6906,69.06
4,20345168,0,4,Floor Supervisor Full Time - TOMMY HILFIGER - ...,Tommy Hilfiger,"Las Vegas, NV",BAAI/bge-small-en-v1.5,0.6944,69.44

# MiniLM

In [11]:
embedder = "sentence-transformers/all-MiniLM-L6-v2"

model_pairs_df, model_topk_df = compute_text_pairs_and_topk(
    resume_df=resume_out,
    job_df=job_out,
    model_name=embedder,
)

Loading weights: 100%|██████████| 103/103 [00:00<00:00, 6778.91it/s]
BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

In [12]:
display(model_topk_df.head())
display(model_pairs_df.head())

,resume_id,resume_idx,job_idx,job_title,company,job_location,model_name,semantic_similarity,final_score,rank
0,20345168,0,1093,Staff Accountant,Accounting Career Consultants & HR Career Cons...,"St Louis, MO",sentence-transformers/all-MiniLM-L6-v2,0.7574,75.74,1
1,20345168,0,698,Sr. Staff Accountant,Robert Half,"Avondale, PA",sentence-transformers/all-MiniLM-L6-v2,0.7345,73.45,2
2,20345168,0,1445,Senior Accountant Tax,Paragon Accountants,"San Diego, CA",sentence-transformers/all-MiniLM-L6-v2,0.7325,73.25,3
3,20345168,0,2436,Sr. Accountant,Robert Half,"Atlanta, GA",sentence-transformers/all-MiniLM-L6-v2,0.7091,70.91,4
4,20345168,0,832,Audit & Accounts Senior,Public Practice Recruitment Ltd - Experts in P...,"Cannock, England, United Kingdom",sentence-transformers/all-MiniLM-L6-v2,0.7086,70.86,5

,resume_id,resume_idx,job_idx,job_title,company,job_location,model_name,semantic_similarity,final_score
0,20345168,0,0,Registered Nurse (RN) at Aveanna,Health eCareers,"Vancouver, WA",sentence-transformers/all-MiniLM-L6-v2,0.2781,27.81
1,20345168,0,1,Locum | Physician Obstetrics and Gynecology,Weatherby Healthcare,"New Richmond, WI",sentence-transformers/all-MiniLM-L6-v2,0.3104,31.04
2,20345168,0,2,Technology Sales (Recruiting) Business Develop...,Proven Recruiting,"Austin, TX",sentence-transformers/all-MiniLM-L6-v2,0.3407,34.07
3,20345168,0,3,Travel RN Oncology 1862.00/week - 23731031EXPP...,TravelNurseSource,"Lexington, KY",sentence-transformers/all-MiniLM-L6-v2,0.1924,19.24
4,20345168,0,4,Floor Supervisor Full Time - TOMMY HILFIGER - ...,Tommy Hilfiger,"Las Vegas, NV",sentence-transformers/all-MiniLM-L6-v2,0.3670,36.70

# MPNet

In [14]:
embedder = "sentence-transformers/all-mpnet-base-v2"

model_pairs_df, model_topk_df = compute_text_pairs_and_topk(
    resume_df=resume_out,
    job_df=job_out,
    model_name=embedder,
)

Loading weights: 100%|██████████| 199/199 [00:00<00:00, 5450.38it/s]
MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

In [15]:
display(model_topk_df.head())
display(model_pairs_df.head())

,resume_id,resume_idx,job_idx,job_title,company,job_location,model_name,semantic_similarity,final_score,rank
0,20345168,0,280,Staff Accountant,Willamette Falls Paper Company,"West Linn, OR",sentence-transformers/all-mpnet-base-v2,0.8409,84.09,1
1,20345168,0,2099,Senior Accountant,Jobot,"Los Angeles, CA",sentence-transformers/all-mpnet-base-v2,0.8409,84.09,2
2,20345168,0,2731,Accountant/Staff Accountant,Intellectt Inc,"Princeton, NJ",sentence-transformers/all-mpnet-base-v2,0.8402,84.02,3
3,20345168,0,1445,Senior Accountant Tax,Paragon Accountants,"San Diego, CA",sentence-transformers/all-mpnet-base-v2,0.8075,80.75,4
4,20345168,0,1093,Staff Accountant,Accounting Career Consultants & HR Career Cons...,"St Louis, MO",sentence-transformers/all-mpnet-base-v2,0.8046,80.46,5

,resume_id,resume_idx,job_idx,job_title,company,job_location,model_name,semantic_similarity,final_score
0,20345168,0,0,Registered Nurse (RN) at Aveanna,Health eCareers,"Vancouver, WA",sentence-transformers/all-mpnet-base-v2,0.4219,42.19
1,20345168,0,1,Locum | Physician Obstetrics and Gynecology,Weatherby Healthcare,"New Richmond, WI",sentence-transformers/all-mpnet-base-v2,0.2469,24.69
2,20345168,0,2,Technology Sales (Recruiting) Business Develop...,Proven Recruiting,"Austin, TX",sentence-transformers/all-mpnet-base-v2,0.4211,42.11
3,20345168,0,3,Travel RN Oncology 1862.00/week - 23731031EXPP...,TravelNurseSource,"Lexington, KY",sentence-transformers/all-mpnet-base-v2,0.3238,32.38
4,20345168,0,4,Floor Supervisor Full Time - TOMMY HILFIGER - ...,Tommy Hilfiger,"Las Vegas, NV",sentence-transformers/all-mpnet-base-v2,0.4452,44.52